// Code generated by MockGen. DO NOT EDIT.
// Source: comm_channel/publisher.go
//
// Generated by this command:
//
//	mockgen -source=comm_channel/publisher.go -destination=internal/mocks/publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ekefan/marbl/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskPublisher is a mock of TaskPublisher interface.
type MockTaskPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockTaskPublisherMockRecorder
	isgomock struct{}
}

// MockTaskPublisherMockRecorder is the mock recorder for MockTaskPublisher.
type MockTaskPublisherMockRecorder struct {
	mock *MockTaskPublisher
}

// NewMockTaskPublisher creates a new mock instance.
func NewMockTaskPublisher(ctrl *gomock.Controller) *MockTaskPublisher {
	mock := &MockTaskPublisher{ctrl: ctrl}
	mock.recorder = &MockTaskPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskPublisher) EXPECT() *MockTaskPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTaskPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTaskPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTaskPublisher)(nil).Close))
}

// Publish mocks base method.
func (m *MockTaskPublisher) Publish(ctx context.Context, task *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockTaskPublisherMockRecorder) Publish(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockTaskPublisher)(nil).Publish), ctx, task)
}
