database:
  dsn: "postgres://marbl:marbl@localhost:5432/marbl"
  migrations_path: "file://storage/migrations"

rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"
  queue_name: "tasks"

producer:
  rate_per_second: 5000
  max_backlog: 100000

metrics:
  port: 9091

profiling:
  port: 6061

logging:
  level: "debug"
  format: "console"