package metrics

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// ProducerMetrics holds all prometheus instruments for the producer service.
type ProducerMetrics struct {
	// TasksProduced is the total number of tasks generated since startup.
	TasksProduced prometheus.Counter
}

// ConsumerMetrics holds all prometheus instruments for the consumer service.
type ConsumerMetrics struct {
	// TasksProcessing is the current number of tasks in processing state.
	TasksProcessing prometheus.Gauge

	// TasksDone is the total number of tasks completed since startup.
	TasksDone prometheus.Counter

	// TasksProcessedByType tracks completed task count per task type (0-9).
	TasksProcessedByType *prometheus.CounterVec

	// ValueSumByType tracks the running sum of task values per type.
	ValueSumByType *prometheus.GaugeVec
}

// NewProducerMetrics creates and registers producer metrics with the given registry.
func NewProducerMetrics(reg prometheus.Registerer) (*ProducerMetrics, error) {
	m := &ProducerMetrics{
		TasksProduced: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "marbl",
			Subsystem: "producer",
			Name:      "tasks_produced_total",
			Help:      "Total number of tasks generated by the producer.",
		}),
	}

	if err := reg.Register(m.TasksProduced); err != nil {
		return nil, fmt.Errorf("register tasks_produced_total: %w", err)
	}

	return m, nil
}

// NewConsumerMetrics creates and registers consumer metrics with the given registry.
func NewConsumerMetrics(reg prometheus.Registerer) (*ConsumerMetrics, error) {
	m := &ConsumerMetrics{
		TasksProcessing: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: "marbl",
			Subsystem: "consumer",
			Name:      "tasks_processing",
			Help:      "Current number of tasks in processing state.",
		}),

		TasksDone: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "marbl",
			Subsystem: "consumer",
			Name:      "tasks_done_total",
			Help:      "Total number of tasks completed by the consumer.",
		}),

		TasksProcessedByType: prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "marbl",
				Subsystem: "consumer",
				Name:      "tasks_processed_by_type_total",
				Help:      "Total number of completed tasks per task type.",
			},
			[]string{"task_type"},
		),

		ValueSumByType: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Namespace: "marbl",
				Subsystem: "consumer",
				Name:      "value_sum_by_type",
				Help:      "Running sum of task values per task type.",
			},
			[]string{"task_type"},
		),
	}

	collectors := []prometheus.Collector{
		m.TasksProcessing,
		m.TasksDone,
		m.TasksProcessedByType,
		m.ValueSumByType,
	}

	for _, c := range collectors {
		if err := reg.Register(c); err != nil {
			return nil, fmt.Errorf("register consumer metric: %w", err)
		}
	}

	return m, nil
}

// Server is a minimal HTTP server that exposes /metrics and nothing else.
type Server struct {
	srv    *http.Server
	logger *slog.Logger
}

// NewServer creates a metrics HTTP server on the given address.
// Registry allows injecting a custom registry (useful in tests).
// Pass prometheus.DefaultRegisterer for production.
func NewServer(addr string, reg prometheus.Gatherer, logger *slog.Logger) *Server {
	mux := http.NewServeMux()
	mux.Handle("/metrics", promhttp.HandlerFor(reg, promhttp.HandlerOpts{
		EnableOpenMetrics: true,
	}))

	return &Server{
		srv: &http.Server{
			Addr:         addr,
			Handler:      mux,
			ReadTimeout:  5 * time.Second,
			WriteTimeout: 10 * time.Second,
		},
		logger: logger,
	}
}

// Start begins serving metrics in the background.
// Returns immediately — use Shutdown to stop.
func (s *Server) Start() {
	go func() {
		s.logger.Info("metrics server listening", slog.String("addr", s.srv.Addr))
		if err := s.srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			s.logger.Error("metrics server error", slog.String("error", err.Error()))
		}
	}()
}

// Shutdown gracefully stops the metrics server.
func (s *Server) Shutdown(ctx context.Context) error {
	return s.srv.Shutdown(ctx)
}